"""empty message

Revision ID: dfef3c89a443
Revises: e0bf254efd9a
Create Date: 2019-10-28 19:00:28.496731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfef3c89a443'
down_revision = 'e0bf254efd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist_genre', ['genre_id', 'artist_id'])
    op.create_unique_constraint(None, 'venue_genre', ['genre_id', 'venue_id'])
    op.add_column('venues', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'deleted')
    op.drop_constraint(None, 'venue_genre', type_='unique')
    op.drop_constraint(None, 'artist_genre', type_='unique')
    # ### end Alembic commands ###
